version: '3.7'
services:

    gradle:
        build:
            context: ./
            dockerfile: src/main/docker/gradle.dockerfile
        image: ds/docker-configuration-gradle
        ports:
            - "8081:8080"

    maven:
        build:
            context: ./
            dockerfile: src/main/docker/maven.dockerfile
        image: ds/docker-configuration-maven
        ports:
            - "8082:8080"
